# Generated by Django 3.1.3 on 2020-11-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201129_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='username',
            field=models.CharField(default=12, max_length=40),
            preserve_default=False,
        ),
    ]
